name: 'Create Release'
description: 'Create a GitHub release'
runs:
  using: 'composite'
  steps:
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: gh release create -t "${{ inputs.title }}" "$(date +%Y%m%d%H%M%S)" --draft --generate-notes
      shell: bash

inputs:
  github-token:
    description: 'GitHub Token for authentication'
    required: true
  title:
    description: 'Title of the release'
    required: true
  GH_TOKEN:
    description: 'GH token'
    required: true
