name: 'Create Release'
description: 'Create a GitHub release'
runs:
  using: 'composite'
  steps:
    - name: Create Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        title: ${{ inputs.title }}

inputs:
  github-token:
    description: 'GitHub Token for authentication'
    required: true
  title:
    description: 'Title of the release'
    required: true
