name: Build Executable with Icon

#on:
#  push:
#    branches:
#      - main
#    paths:
#      - 'CollagePDFCreator.py'
#      - 'placement.py'
#      - 'images/**'
#      - 'locales/**'

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Convert PNG to ICO (Windows) and PNG to ICNS (macOS)
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            python -c "from PIL import Image; Image.open('images/logo.png').save('images/logo.ico')"
          elif [ "${{ runner.os }}" == "macOS" ]; then
            mkdir images/logo.iconset
            sips -z 16 16     images/logo.png --out images/logo.iconset/icon_16x16.png
            sips -z 32 32     images/logo.png --out images/logo.iconset/icon_16x16@2x.png
            sips -z 32 32     images/logo.png --out images/logo.iconset/icon_32x32.png
            sips -z 64 64     images/logo.png --out images/logo.iconset/icon_32x32@2x.png
            sips -z 128 128   images/logo.png --out images/logo.iconset/icon_128x128.png
            sips -z 256 256   images/logo.png --out images/logo.iconset/icon_128x128@2x.png
            sips -z 256 256   images/logo.png --out images/logo.iconset/icon_256x256.png
            sips -z 512 512   images/logo.png --out images/logo.iconset/icon_256x256@2x.png
            sips -z 512 512   images/logo.png --out images/logo.iconset/icon_512x512.png
            iconutil -c icns images/logo.iconset -o images/logo.icns
            rm -R images/logo.iconset
          fi
        shell: bash

      - name: Build executable
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            icon_ext="ico"
            data_string=(images\;images locales\;locales)
          elif [ "${{ runner.os }}" == "macOS" ]; then
            icon_ext="icns"
            data_string=(images:images locales:locales)
          else
            icon_ext="png"
            data_string=(images:images locales:locales)
          fi
          pyinstaller --onefile --windowed --icon=images/logo.$icon_ext --add-data ${data_string[0]} --add-data ${data_string[1]} CollagePDFCreator.py
          ls -lR
          python -V
          cat CollagePDFCreator.spec
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-executable
          path: dist/
