name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: ./.github/actions/create-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag-name: ${{ github.ref_name }}
          release-name: Release ${{ github.ref_name }}
          body: 'New release ${{ github.ref_name }}'

  upload-release:
    needs: prepare-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Restore cached artifacts
        id: 'cached-artifacts'
        uses: actions/cache/restore@v4
        with:
          path: dist/*
          key: '${{ runner.os }}-executable-${{ github.sha }}'

      - name: Upload Release Artifacts
        uses: ./.github/actions/upload-release-artifacts
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          upload-url: ${{ needs.prepare-release.steps.create_release.outputs.upload_url }}
          artifact-name: '${{ runner.os }}-executable'
          artifact-path: dist/*
